#!/bin/bash
set -euo pipefail

# stunt-from-testdata: Generates corpora from boris-testdata into /tmp.
# Solipsist does not commit large synthetic corpora; this generates on-demand.

TARGET_DIR="${1:-/tmp/solipsist-testdata-corpus}"

echo "==> Generating synthetic testdata into $TARGET_DIR"
mkdir -p "$TARGET_DIR"

cat << 'EOF' > "$TARGET_DIR/index.md"
---
title: Synthetic Root
status: published
---
# Synthetic Root
Generated by stunt-from-testdata.sh for high-volume graph testing.
EOF

for i in {1..20}; do
cat << EOF > "$TARGET_DIR/page-$i.md"
---
title: Page $i
parent: index
---
# Page $i
Content for page $i with reference to [[index]].
EOF
done

echo "==> Generated 21 test pages in $TARGET_DIR"
